// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.4
// source: cloud/v1/messages.proto

package cloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgType 表示 WSS JSON 信封中的 type 字段语义。
// 线网字符串由生成代码的 MsgType_name 推导：去掉 MSG_TYPE_ 前缀再转小写
// （如 MSG_TYPE_GATEWAY_HELLO → gateway_hello）。见各服务 TypeName/ParseType。
// 信封格式：{"type":"<wire string>","payload":{...}}
type MsgType int32

const (
	MsgType_MSG_TYPE_UNSPECIFIED      MsgType = 0
	MsgType_MSG_TYPE_GATEWAY_HELLO    MsgType = 1
	MsgType_MSG_TYPE_DEVICE_REGISTER  MsgType = 2
	MsgType_MSG_TYPE_DEVICE_HEARTBEAT MsgType = 3
	MsgType_MSG_TYPE_DEVICE_OFFLINE   MsgType = 4
	MsgType_MSG_TYPE_COMMAND          MsgType = 5 // SaaS → Gateway
	MsgType_MSG_TYPE_COMMAND_RESULT   MsgType = 6 // Gateway → SaaS
	MsgType_MSG_TYPE_EVENT            MsgType = 7
	MsgType_MSG_TYPE_CAPABILITY       MsgType = 8
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MSG_TYPE_UNSPECIFIED",
		1: "MSG_TYPE_GATEWAY_HELLO",
		2: "MSG_TYPE_DEVICE_REGISTER",
		3: "MSG_TYPE_DEVICE_HEARTBEAT",
		4: "MSG_TYPE_DEVICE_OFFLINE",
		5: "MSG_TYPE_COMMAND",
		6: "MSG_TYPE_COMMAND_RESULT",
		7: "MSG_TYPE_EVENT",
		8: "MSG_TYPE_CAPABILITY",
	}
	MsgType_value = map[string]int32{
		"MSG_TYPE_UNSPECIFIED":      0,
		"MSG_TYPE_GATEWAY_HELLO":    1,
		"MSG_TYPE_DEVICE_REGISTER":  2,
		"MSG_TYPE_DEVICE_HEARTBEAT": 3,
		"MSG_TYPE_DEVICE_OFFLINE":   4,
		"MSG_TYPE_COMMAND":          5,
		"MSG_TYPE_COMMAND_RESULT":   6,
		"MSG_TYPE_EVENT":            7,
		"MSG_TYPE_CAPABILITY":       8,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_messages_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_cloud_v1_messages_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_messages_proto_rawDescGZIP(), []int{0}
}

type GatewayHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayHello) Reset() {
	*x = GatewayHello{}
	mi := &file_cloud_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayHello) ProtoMessage() {}

func (x *GatewayHello) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayHello.ProtoReflect.Descriptor instead.
func (*GatewayHello) Descriptor() ([]byte, []int) {
	return file_cloud_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayHello) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

type DeviceRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	GatewayId     string                 `protobuf:"bytes,4,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRegister) Reset() {
	*x = DeviceRegister{}
	mi := &file_cloud_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRegister) ProtoMessage() {}

func (x *DeviceRegister) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRegister.ProtoReflect.Descriptor instead.
func (*DeviceRegister) Descriptor() ([]byte, []int) {
	return file_cloud_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceRegister) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceRegister) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DeviceRegister) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DeviceRegister) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

type DeviceHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TsUnixMs      int64                  `protobuf:"varint,2,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	GatewayId     string                 `protobuf:"bytes,4,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceHeartbeat) Reset() {
	*x = DeviceHeartbeat{}
	mi := &file_cloud_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceHeartbeat) ProtoMessage() {}

func (x *DeviceHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceHeartbeat.ProtoReflect.Descriptor instead.
func (*DeviceHeartbeat) Descriptor() ([]byte, []int) {
	return file_cloud_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceHeartbeat) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceHeartbeat) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *DeviceHeartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceHeartbeat) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

type DeviceOffline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	GatewayId     string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceOffline) Reset() {
	*x = DeviceOffline{}
	mi := &file_cloud_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceOffline) ProtoMessage() {}

func (x *DeviceOffline) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceOffline.ProtoReflect.Descriptor instead.
func (*DeviceOffline) Descriptor() ([]byte, []int) {
	return file_cloud_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceOffline) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceOffline) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CmdId         string                 `protobuf:"bytes,2,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Args          string                 `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_cloud_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_cloud_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Command) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *Command) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Command) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CmdId         string                 `protobuf:"bytes,2,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_cloud_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_cloud_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResult) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CommandResult) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *CommandResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommandResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeviceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	TsUnixMs      int64                  `protobuf:"varint,5,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	GatewayId     string                 `protobuf:"bytes,6,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceEvent) Reset() {
	*x = DeviceEvent{}
	mi := &file_cloud_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceEvent) ProtoMessage() {}

func (x *DeviceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceEvent.ProtoReflect.Descriptor instead.
func (*DeviceEvent) Descriptor() ([]byte, []int) {
	return file_cloud_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeviceEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceEvent) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *DeviceEvent) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *DeviceEvent) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

type DeviceCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	GatewayId     string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Entries       []*CapabilityEntry     `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCapability) Reset() {
	*x = DeviceCapability{}
	mi := &file_cloud_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCapability) ProtoMessage() {}

func (x *DeviceCapability) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCapability.ProtoReflect.Descriptor instead.
func (*DeviceCapability) Descriptor() ([]byte, []int) {
	return file_cloud_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceCapability) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceCapability) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *DeviceCapability) GetEntries() []*CapabilityEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CapabilityEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	RiskHint      string                 `protobuf:"bytes,2,opt,name=risk_hint,json=riskHint,proto3" json:"risk_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityEntry) Reset() {
	*x = CapabilityEntry{}
	mi := &file_cloud_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityEntry) ProtoMessage() {}

func (x *CapabilityEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityEntry.ProtoReflect.Descriptor instead.
func (*CapabilityEntry) Descriptor() ([]byte, []int) {
	return file_cloud_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *CapabilityEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CapabilityEntry) GetRiskHint() string {
	if x != nil {
		return x.RiskHint
	}
	return ""
}

var File_cloud_v1_messages_proto protoreflect.FileDescriptor

const file_cloud_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x17cloud/v1/messages.proto\x12\bcloud.v1\"-\n" +
	"\fGatewayHello\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\"p\n" +
	"\x0eDeviceRegister\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x04 \x01(\tR\tgatewayId\"\x83\x01\n" +
	"\x0fDeviceHeartbeat\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x02 \x01(\x03R\btsUnixMs\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x04 \x01(\tR\tgatewayId\"K\n" +
	"\rDeviceOffline\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\"i\n" +
	"\aCommand\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x15\n" +
	"\x06cmd_id\x18\x02 \x01(\tR\x05cmdId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x12\n" +
	"\x04args\x18\x04 \x01(\tR\x04args\"m\n" +
	"\rCommandResult\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x15\n" +
	"\x06cmd_id\x18\x02 \x01(\tR\x05cmdId\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xb9\x01\n" +
	"\vDeviceEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x05 \x01(\x03R\btsUnixMs\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x06 \x01(\tR\tgatewayId\"\x83\x01\n" +
	"\x10DeviceCapability\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\x123\n" +
	"\aentries\x18\x03 \x03(\v2\x19.cloud.v1.CapabilityEntryR\aentries\"F\n" +
	"\x0fCapabilityEntry\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1b\n" +
	"\trisk_hint\x18\x02 \x01(\tR\briskHint*\xf9\x01\n" +
	"\aMsgType\x12\x18\n" +
	"\x14MSG_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MSG_TYPE_GATEWAY_HELLO\x10\x01\x12\x1c\n" +
	"\x18MSG_TYPE_DEVICE_REGISTER\x10\x02\x12\x1d\n" +
	"\x19MSG_TYPE_DEVICE_HEARTBEAT\x10\x03\x12\x1b\n" +
	"\x17MSG_TYPE_DEVICE_OFFLINE\x10\x04\x12\x14\n" +
	"\x10MSG_TYPE_COMMAND\x10\x05\x12\x1b\n" +
	"\x17MSG_TYPE_COMMAND_RESULT\x10\x06\x12\x12\n" +
	"\x0eMSG_TYPE_EVENT\x10\a\x12\x17\n" +
	"\x13MSG_TYPE_CAPABILITY\x10\bB*Z(saas-server/internal/pb/cloud/v1;cloudv1b\x06proto3"

var (
	file_cloud_v1_messages_proto_rawDescOnce sync.Once
	file_cloud_v1_messages_proto_rawDescData []byte
)

func file_cloud_v1_messages_proto_rawDescGZIP() []byte {
	file_cloud_v1_messages_proto_rawDescOnce.Do(func() {
		file_cloud_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_v1_messages_proto_rawDesc), len(file_cloud_v1_messages_proto_rawDesc)))
	})
	return file_cloud_v1_messages_proto_rawDescData
}

var file_cloud_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cloud_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cloud_v1_messages_proto_goTypes = []any{
	(MsgType)(0),             // 0: cloud.v1.MsgType
	(*GatewayHello)(nil),     // 1: cloud.v1.GatewayHello
	(*DeviceRegister)(nil),   // 2: cloud.v1.DeviceRegister
	(*DeviceHeartbeat)(nil),  // 3: cloud.v1.DeviceHeartbeat
	(*DeviceOffline)(nil),    // 4: cloud.v1.DeviceOffline
	(*Command)(nil),          // 5: cloud.v1.Command
	(*CommandResult)(nil),    // 6: cloud.v1.CommandResult
	(*DeviceEvent)(nil),      // 7: cloud.v1.DeviceEvent
	(*DeviceCapability)(nil), // 8: cloud.v1.DeviceCapability
	(*CapabilityEntry)(nil),  // 9: cloud.v1.CapabilityEntry
}
var file_cloud_v1_messages_proto_depIdxs = []int32{
	9, // 0: cloud.v1.DeviceCapability.entries:type_name -> cloud.v1.CapabilityEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cloud_v1_messages_proto_init() }
func file_cloud_v1_messages_proto_init() {
	if File_cloud_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_v1_messages_proto_rawDesc), len(file_cloud_v1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_v1_messages_proto_goTypes,
		DependencyIndexes: file_cloud_v1_messages_proto_depIdxs,
		EnumInfos:         file_cloud_v1_messages_proto_enumTypes,
		MessageInfos:      file_cloud_v1_messages_proto_msgTypes,
	}.Build()
	File_cloud_v1_messages_proto = out.File
	file_cloud_v1_messages_proto_goTypes = nil
	file_cloud_v1_messages_proto_depIdxs = nil
}
