// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.4
// source: board/v1/messages.proto

package boardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	MsgId string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Register
	//	*Envelope_Heartbeat
	//	*Envelope_Command
	//	*Envelope_CommandResult
	//	*Envelope_Event
	//	*Envelope_Capability
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_board_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_board_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Envelope) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Envelope) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *Envelope) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *Envelope) GetCapability() *Capability {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Capability); ok {
			return x.Capability
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Register struct {
	Register *Register `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type Envelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type Envelope_Command struct {
	Command *Command `protobuf:"bytes,12,opt,name=command,proto3,oneof"`
}

type Envelope_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,13,opt,name=command_result,json=commandResult,proto3,oneof"`
}

type Envelope_Event struct {
	Event *Event `protobuf:"bytes,14,opt,name=event,proto3,oneof"`
}

type Envelope_Capability struct {
	Capability *Capability `protobuf:"bytes,15,opt,name=capability,proto3,oneof"`
}

func (*Envelope_Register) isEnvelope_Payload() {}

func (*Envelope_Heartbeat) isEnvelope_Payload() {}

func (*Envelope_Command) isEnvelope_Payload() {}

func (*Envelope_CommandResult) isEnvelope_Payload() {}

func (*Envelope_Event) isEnvelope_Payload() {}

func (*Envelope_Capability) isEnvelope_Payload() {}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_board_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_board_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Register) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Register) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Register) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TsUnixMs      int64                  `protobuf:"varint,2,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_board_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_board_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Heartbeat) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CmdId         string                 `protobuf:"bytes,2,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Args          string                 `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	RiskClass     string                 `protobuf:"bytes,5,opt,name=risk_class,json=riskClass,proto3" json:"risk_class,omitempty"` // safe|sensitive|high; optional
	FlowId        string                 `protobuf:"bytes,6,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`          // required for ui.* when enforced later
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_board_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_board_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Command) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *Command) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Command) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *Command) GetRiskClass() string {
	if x != nil {
		return x.RiskClass
	}
	return ""
}

func (x *Command) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CmdId         string                 `protobuf:"bytes,2,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_board_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_board_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CommandResult) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CommandResult) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *CommandResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommandResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	TsUnixMs      int64                  `protobuf:"varint,5,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_board_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_board_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *Event) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

type CapabilityEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	RiskHint      string                 `protobuf:"bytes,2,opt,name=risk_hint,json=riskHint,proto3" json:"risk_hint,omitempty"` // safe|sensitive|high
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityEntry) Reset() {
	*x = CapabilityEntry{}
	mi := &file_board_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityEntry) ProtoMessage() {}

func (x *CapabilityEntry) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityEntry.ProtoReflect.Descriptor instead.
func (*CapabilityEntry) Descriptor() ([]byte, []int) {
	return file_board_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *CapabilityEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CapabilityEntry) GetRiskHint() string {
	if x != nil {
		return x.RiskHint
	}
	return ""
}

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Entries       []*CapabilityEntry     `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_board_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_board_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_board_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Capability) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Capability) GetEntries() []*CapabilityEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_board_v1_messages_proto protoreflect.FileDescriptor

const file_board_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x17board/v1/messages.proto\x12\bboard.v1\"\xe5\x02\n" +
	"\bEnvelope\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x120\n" +
	"\bregister\x18\n" +
	" \x01(\v2\x12.board.v1.RegisterH\x00R\bregister\x123\n" +
	"\theartbeat\x18\v \x01(\v2\x13.board.v1.HeartbeatH\x00R\theartbeat\x12-\n" +
	"\acommand\x18\f \x01(\v2\x11.board.v1.CommandH\x00R\acommand\x12@\n" +
	"\x0ecommand_result\x18\r \x01(\v2\x17.board.v1.CommandResultH\x00R\rcommandResult\x12'\n" +
	"\x05event\x18\x0e \x01(\v2\x0f.board.v1.EventH\x00R\x05event\x126\n" +
	"\n" +
	"capability\x18\x0f \x01(\v2\x14.board.v1.CapabilityH\x00R\n" +
	"capabilityB\t\n" +
	"\apayload\"K\n" +
	"\bRegister\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"^\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x02 \x01(\x03R\btsUnixMs\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xa1\x01\n" +
	"\aCommand\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x15\n" +
	"\x06cmd_id\x18\x02 \x01(\tR\x05cmdId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x12\n" +
	"\x04args\x18\x04 \x01(\tR\x04args\x12\x1d\n" +
	"\n" +
	"risk_class\x18\x05 \x01(\tR\triskClass\x12\x17\n" +
	"\aflow_id\x18\x06 \x01(\tR\x06flowId\"m\n" +
	"\rCommandResult\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x15\n" +
	"\x06cmd_id\x18\x02 \x01(\tR\x05cmdId\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x94\x01\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x05 \x01(\x03R\btsUnixMs\"F\n" +
	"\x0fCapabilityEntry\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1b\n" +
	"\trisk_hint\x18\x02 \x01(\tR\briskHint\"^\n" +
	"\n" +
	"Capability\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x123\n" +
	"\aentries\x18\x02 \x03(\v2\x19.board.v1.CapabilityEntryR\aentriesB*Z(board-agent/internal/pb/board/v1;boardv1b\x06proto3"

var (
	file_board_v1_messages_proto_rawDescOnce sync.Once
	file_board_v1_messages_proto_rawDescData []byte
)

func file_board_v1_messages_proto_rawDescGZIP() []byte {
	file_board_v1_messages_proto_rawDescOnce.Do(func() {
		file_board_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_board_v1_messages_proto_rawDesc), len(file_board_v1_messages_proto_rawDesc)))
	})
	return file_board_v1_messages_proto_rawDescData
}

var file_board_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_board_v1_messages_proto_goTypes = []any{
	(*Envelope)(nil),        // 0: board.v1.Envelope
	(*Register)(nil),        // 1: board.v1.Register
	(*Heartbeat)(nil),       // 2: board.v1.Heartbeat
	(*Command)(nil),         // 3: board.v1.Command
	(*CommandResult)(nil),   // 4: board.v1.CommandResult
	(*Event)(nil),           // 5: board.v1.Event
	(*CapabilityEntry)(nil), // 6: board.v1.CapabilityEntry
	(*Capability)(nil),      // 7: board.v1.Capability
}
var file_board_v1_messages_proto_depIdxs = []int32{
	1, // 0: board.v1.Envelope.register:type_name -> board.v1.Register
	2, // 1: board.v1.Envelope.heartbeat:type_name -> board.v1.Heartbeat
	3, // 2: board.v1.Envelope.command:type_name -> board.v1.Command
	4, // 3: board.v1.Envelope.command_result:type_name -> board.v1.CommandResult
	5, // 4: board.v1.Envelope.event:type_name -> board.v1.Event
	7, // 5: board.v1.Envelope.capability:type_name -> board.v1.Capability
	6, // 6: board.v1.Capability.entries:type_name -> board.v1.CapabilityEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_board_v1_messages_proto_init() }
func file_board_v1_messages_proto_init() {
	if File_board_v1_messages_proto != nil {
		return
	}
	file_board_v1_messages_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Register)(nil),
		(*Envelope_Heartbeat)(nil),
		(*Envelope_Command)(nil),
		(*Envelope_CommandResult)(nil),
		(*Envelope_Event)(nil),
		(*Envelope_Capability)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_board_v1_messages_proto_rawDesc), len(file_board_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_board_v1_messages_proto_goTypes,
		DependencyIndexes: file_board_v1_messages_proto_depIdxs,
		MessageInfos:      file_board_v1_messages_proto_msgTypes,
	}.Build()
	File_board_v1_messages_proto = out.File
	file_board_v1_messages_proto_goTypes = nil
	file_board_v1_messages_proto_depIdxs = nil
}
